language: go
go:
- 1.11.x
deploy:
  provider: heroku
  api_key:
    secure: d3hTugpKxkiQJdoIzWql6JZCk3E/rkkURg3KOiXIqUZ7NXWZ30JlZJ/46Ju2yX3q549RrET0q+5fF3SRowxbrKkRXmz50FjmxhKJzL9GWLMWDGKwsD05rn4uulhctjorhXiBhJFK07R8y8+gE1zVChPnFcL2aLyqNNXgsnfZjQ/l+rgAcPze87453TuHOPwrOD/k21wKxqnUjLnrdN54yJR8Gg7JJCbiQglLg42bO5Sd9nuwpjcOZaXFY0jeTJ2GuOU/8bnQRByrqwRsHbAdtlAm968TyoaLcfELGoTGCbRyQyvWBdkExYgtz++K7+fl3G9CJlCE2MenCcSpkavHcv2motZ5pvaqP2FuuA1X7gcjKe+76jPz3SHqm3iI+dVWA3cewwet5Cv0SPo4eS5nWquBuTT7M1sZU6tgWwTlizZN8zII3a52MaVmuJjto2j6hdWa385IlT4NWs785Fz5R36kivnIu2GqMLhDtnh/N9UkpKwqKH2QRm9ataA3HHtbK+3YU79svhzlw/1bxLV0gMOUzA0lOQS9KmMkxn5sPg9GajSP5Avr5Uc6oJDvKPljOrIxqdj0jhhvoXVBEMHHaAWy/okz2FEpfEpl8oZcI+UuVgmfXdPtD/s5+k2VPzDUoKzL0vdmEOcO856qRVaFTmvDMsd4ayvWWRlY2fYpMPs=
