language: go
go:
- 1.11.x
deploy:
  provider: heroku
  api_key:
    secure: QJwsMcPBW5nqbugUjuHU5DaxjpBhw9FK1pdUr2KpIvZrUaOgm3BNXN95LPxug5gMAz75gEnkpPoU3HTrdNgl73GysSxLYmT+ri8HFu/4xvfPP6c/2s2FmvCcnGSorclms4wEt70bf+u1ruD03SZa0UnJF/FA/Wm/Rve5ibRlCkXv8/t71BxTHF62yw8qv4iYyGY55tw5e6YKK1XoDXCi0828G+sAq51Bj/FYSyo2GPKHlMNyu4UgB/IRJlpkaBMyEzPfv2ko8efFYk68zUCV3VF3blvPD1Nh5aRazioGfjFE0trELkYRtYvgPqTNaqX2EShNUhltjSzbR9u7BOeR+XoErbpm8POroUR7iKbUI04D+VftAYC84rPvh2VI1dGTUMmhcQh9+di/GzGXgzlxlOCBquktoESUwmu/X30p54aWH1eiBFjikgthZ9UcQlIaFYS9y5Iy2p1sR1BwZo/ees4A4SgsCUsN7e+wwCYGj6QYBzLilFm8aFWkAA9fQX/1rnH9vSJ49Mh+BuR3afEyaFFbUP8F0ILfZlPWAh4pgK6XlJL53IyPlCZQQS2w1rMKT1QMnueDy5YZksoWA8vaTaTxlu05EyuNqLw4dSh6H8No2WEyNZmjreDfgnV0WbpwsCnGdAySTLxICnFKrw5lvgv89B4AdQN6k1jKlEVTK/w=
