language: go
go:
- 1.11.x
deploy:
  provider: heroku
  api_key:
    secure: O65k63waCDhObqDeEx+GaRkfNdD7APVg8QIghVPh3zLS4LiIsgg9zof8hyy04dnMKwLjgMkm1sRPpTaJ5v6rUGqpuS6ioOw9QW2OscIdF4cf/GESQwyQletsPLfwS3YOMeyXMF9QAyUKfGSyClP5Ext8i9SlUWyOzZJKKEYkuXyT1P9BZxtGklU8DOBxD0AlQD7aLGmq3y7+07dGfeTWoc5ZYN6NznmyON+uTC1piX9GVqWgTdkhh8lj5Bccsrr6AUDd3ovtxj4lHUfHQ8iMRBrE3yoG6r8p8sHx0WfczSIuTt9XztbkNRmcqncAs8miToCYbaao+nagnFLyiYV9FOhAQtCc2DJxr3NF32UE4z41ovYzPJQAnicBPo1hlUhrryt6S1zjbtIGeHT4eyldY9YW8DMzMhh1TSf8xKmHSoUnA1FEcMqM6mVfDu4mbrjInqRxUPtR7RZ7oWurW2yn3S7eo3G1JehqNf/mL90MfY6+JQkdppCTJc3OEb0y8/wRR/7XKx8ohSwy4ObiC9HZgIVONsZ9UNJFIYFPLTmzpjvuQnnhPATU3O4vPB0cr0V4pSM8AGEII2Y/VA2+VsuMq3P0bkxug0hByTqEIhSlArOiLi1hLhh6qyBL5Q/vuO+dtB1dz9yPdBQcGA+7H8uM+j/zrSG8OPLdKEqlgty/EWI=
